name: OverPy Behavior Testing
on:
    push:
        branches:
            - master
    pull_request: {}

env:
    HUSKY: 0

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22.4
                  cache: npm
            - uses: actions/cache/restore@v4
              with:
                  key: ${{ github.run_id }}-node-modules
                  path: |
                      node_modules
            - name: Install dependencies
              run: |
                  npm install
            - name: Run tests
              run: |
                  npm run test
